---
# This file will be used to upgrade all services
# Any of these variables can be overwritten by upgrade-vars.yml

# Specify the deployment tool of an existing OpenStack cloud that will
# be upgraded
project: tripleo


##############
# Update vars
##############
update_services: no

openstack_services:
  - keystone
  - glance
  - cinder


##############################
# PROJECT SPECIFIC VARIABLES #
##############################

##########
# Tripleo
##########
undercloud_credentials: "/home/stack/stackrc"
pacemaker_managed_services:
  - cinder-volume
delorean_repo_url: http://buildlogs.centos.org/centos/7/cloud/x86_64/rdo-trunk-master/delorean.repo
