---
- name: Gathering overcloud information
  get-heat-output:

- stat: path=/tmp/upgrade-information
  register: info
  failed_when: info.stat.exists == False

- stat: path=/tmp/node-information
  register: nodes
  failed_when: nodes.stat.exists == False

- name: Generating inventory file
  generate-tripleo-inventory:
  become: yes
