---
- include: "{{ playbook_dir }}/roles/{{ item }}/tasks/systemd_stop_services.yml"
  serial: "30%"
  when: "'mariadb' != item"
  with_items: "{{ openstack_services }}"

- include: "{{ playbook_dir }}/roles/{{ item.split('-')[0] }}/tasks/pacemaker_stop_services.yml"
  serial: "30%"
  when: "'mariadb' != item"
  with_items: "{{ pacemaker_managed_services }}"

# Always stop the database service last
- include: "{{ playbook_dir }}/roles/mariadb/tasks/systemd_stop_services.yml"
  serial: "30%"
  when: "'mariadb' in openstack_services"

- include: "{{ playbook_dir }}/roles/mariadb/pacemaker_stop_services.yml"
  serial: "30%"
  when: "'mariadb' in pacemaker_managed_services"

- include: "{{ playbook_dir }}/roles/pacemaker/tasks/shutdown_pacemaker.yml"
