---
- include: "{{ playbook_dir }}/roles/{{ item }}/tasks/systemd_stop_services.yml"
  serial: "30%"
  with_items: "{{ openstack_services }}"

- include: "{{ playbook_dir }}/roles/{{ item.split('-')[0] }}/tasks/pacemaker_stop_services.yml"
  serial: "30%"
  with_items: "{{ pacemaker_managed_services }}"

- include: "{{ playbook_dir }}/roles/pacemaker/tasks/shutdown_pacemaker.yml"
