---
- include: stop_services.yml

- include: shutdown_database.yml

- include: shutdown_pacemaker.yml

- include: update_packages.yml

- include: startup_database.yml

- include: sync_database.yml
  when: "{{ not update_services | bool }}"

- include: start_services.yml
