---
- include: stop_services.yml

- include: disable_fencing.yml

- include: database_backup.yml

# Always stop the database service last
- include: stop_mariadb.yml

- include: move_data.yml

- include: shutdown_pacemaker.yml

- include: update_packages.yml

- include: startup_database.yml

- include: sync_database.yml
  when: "{{ not update_services | bool }}"

- include: start_services.yml
