---
- include: stop_services.yml

- include: disable_fencing.yml

# Database management is always stopped last and started first
- include: mariadb_upgrade.yml

- include: update_packages.yml

- include: sync_database.yml
  when: "{{ not update_services | bool }}"

- include: start_services.yml
