---
- name: Run Ironic DB sync
  shell: ironic-manage db_sync
  run_once: true
  become: true
  when: "inventory_hostname in groups['ironic-api']
        and {{ not update_services | bool }}"
  tags: ironic_db_sync
