---
- include: pacemaker.yml
  when: "'ironic-api' in pacemaker_managed_services
        or 'ironic-conductor' in pacemaker_managed_services
        or 'ironic-inspector-dnsmasq' in pacemaker_managed_services
        or 'ironic-inspector' in pacemaker_managed_services"
  tags: ironic_pacemaker_tasks

- include: systemd.yml
  when: "'ironic-api' not in pacemaker_managed_services
        or 'ironic-conductor' not in pacemaker_managed_services
        or 'ironic-inspector-dnsmasq' not in pacemaker_managed_services
        or 'ironic-inspector' not in pacemaker_managed_services"
  tags: ironic_systemd_tasks
