---
- name: Update ironic API package
  yum:
    name: openstack-ironic-api
    state: latest
  when: "inventory_hostname in groups['ironic-api']"
  become: true
  tags: ironic_package_update

- name: Update ironic conductor package
  yum:
    name: openstack-ironic-conductor
    state: latest
  when: "inventory_hostname in groups['ironic-conductor']"
  become: true
  tags: ironic_package_update

- name: Update ironic inspector package
  yum:
    name: openstack-ironic-inspector
    state: latest
  when: "inventory_hostname in groups['ironic-inspector']"
  become: true
  tags: ironic_package_update

- name: Update python ironic package
  yum:
    name: python-ironic-lib
    state: latest
  when: "inventory_hostname in groups['ironic-api']
         or inventory_hostname in groups['ironic-conductor']
         or inventory_hostname in groups['ironic-inspector']"
  become: true
  tags: ironic_package_update
