---
- name: Starting glance-api service
  command: "/usr/sbin/pcs resource enable openstack-glance-api"
  run_once: true
  when: "inventory_hostname in groups['glance-api']
        and 'glance-api' in pacemaker_managed_services"

- name: Starting glance-registry service
  command: "/usr/sbin/pcs resource enable openstack-glance-registry"
  run_once: true
  when: "inventory_hostname in groups ['glance-registry']
        and 'glance-registry' in pacemaker_managed_services"

- name: Waiting for cluster to settle
  command: /usr/sbin/crm_resource --wait
  run_once: true
