---
- include: pacemaker.yml
  when: "'glance-api' in pacemaker_managed_services
        or 'glance-registry' in pacemaker_managed_services"

- include: systemd.yml
  when: "'glance-api' not in pacemaker_managed_services
        or 'glance-registry' not in pacemaker_managed_services"
