---
- debug: var="pacemaker_managed_services"

- debug: var="inventory_hostname"

- include: pacemaker.yml
  when: "inventory_hostname in groups[item]"
  
  with_items: "{{ pacemaker_managed_services }}"

- include: systemd.yml
  when: "inventory_hostname not in groups[pacemaker_managed_services]"
