---
- name: Starting Cinder API service
  command: "/usr/sbin/pcs resource enable openstack-cinder-api"
  run_once: true
  when: "inventory_hostname in groups ['cinder-api']
        and 'cinder-api' in pacemaker_managed_services"

- name: Stopping Cinder Scheduler service
  command: "/usr/sbin/pcs resource enable openstack-cinder-scheduler"
  run_once: true
  when: "inventory_hostname in groups ['cinder-scheduler']
        and 'cinder-scheduler' in pacemaker_managed_services"

- name: Stopping Cinder Volumes service
  command: "/usr/sbin/pcs resource enable openstack-cinder-volume"
  run_once: true
  when: "inventory_hostname in groups ['cinder-volumes']
        and 'cinder-volumes' in pacemaker_managed_services"
