---
- name: Starting Cinder API service
  service:
    name: openstack-cinder-api
    state: started
  when: "inventory_hostname in groups ['cinder-api']
        and 'cinder-api' not in pacemaker_managed_services"
  tags: cinder_api_systemd_start

- name: Starting Cinder Scheduler service
  service:
    name: openstack-cinder-scheduler
    state: started
  when: "inventory_hostname in groups ['cinder-scheduler']
        and 'cinder-scheduler' not in pacemaker_managed_services"
  tags: cinder_scheduler_systemd_start

- name: Starting Cinder Volume service
  service:
    name: openstack-cinder-volume
    state: started
  when: "inventory_hostname in groups ['cinder-volume']
        and 'cinder-volume' not in pacemaker_managed_services"
  tags: cinder_volume_systemd_start
