---
- name: Starting Cinder API service
  service:
    name: openstack-cinder-api
    state: started
  when: "inventory_hostname in groups ['cinder-api']
        and 'cinder-api' not in pacemaker_managed_services"

- name: Starting Cinder Scheduler service
  service:
    name: openstack-cinder-scheduler
    state: started
  when: "inventory_hostname in groups ['cinder-scheduler']
        and 'cinder-scheduler' not in pacemaker_managed_services"

- name: Starting Cinder Volumes service
  service:
    name: openstack-cinder-volumes
    state: started
  when: "inventory_hostname in groups ['cinder-volumes']
        and 'cinder-volumes' not in pacemaker_managed_services"
