---
- include: stop_services.yml

- include: "{{ playbook_dir }}/roles/pacemaker/tasks/stop_services.yml"

- include: update_packages.yml

- include: sync_database.yml

- include: "{{ playbook_dir }}/roles/pacemaker/tasks/start_services.yml"

- include: start_services.yml
