---
- name: Update Cinder packages
  yum:
    name: openstack-cinder
    state: latest
  when: "inventory_hostname in groups['cinder-api']
         or inventory_hostname in groups['cinder-volume']
         or inventory_hostname in groups['cinder-scheduler']"
  become: true
  tags: cinder_package_update

- name: Update python cinder packages
  yum:
    name: python-cinder
    state: latest
  when: "inventory_hostname in groups['cinder-api']
         or inventory_hostname in groups['cinder-volume']
         or inventory_hostname in groups['cinder-scheduler']"
  become: true
  tags: cinder_package_update
