---
- name: Starting sahara-api service
  service:
    name: openstack-sahara-api
    state: started
  become: yes
  when: "inventory_hostname in groups['sahara-api']
        and 'sahara-api' not in pacemaker_managed_services"
  tags: sahara_api_systemd_start

- name: Starting sahara-engine service
  service:
    name: openstack-sahara-engine
    state: started
  become: yes
  when: "inventory_hostname in groups['sahara-engine']
        and 'sahara-engine' not in pacemaker_managed_services"
  tags: sahara_engine_systemd_start
