---
- include: pacemaker.yml
  when: "'sahara-api' in pacemaker_managed_services
        or 'sahara-engine' in pacemaker_managed_services"
  tags: sahara_pacemaker_tasks

- include: systemd.yml
  when: "'sahara-api' not in pacemaker_managed_services
        or 'sahara-engine' not in pacemaker_managed_services"
  tags: sahara_systemd_tasks
