---
- hosts: all
  roles:
    - { role: puppet_modules,
        tags: puppet_modules }

- hosts: keystone
  roles:
    - { role: keystone,
        tags: keystone,
        when: "'keystone' in openstack_services" }

- hosts:
    - glance-api
    - glance-registry
  roles:
    - { role: glance,
        tags: glance,
        when: "'glance' in openstack_services" }

- hosts:
    - cinder-api
    - cinder-scheduler
    - cinder-volume
  roles:
    - { role: cinder,
        tags: cinder,
        when: "'cinder' in openstack_services" }

- hosts:
    - heat-api
    - heat-api-cfn
    - heat-api-cloudwatch
    - heat-engine
  roles:
    - { role: heat,
        tags: heat,
        when: "'heat' in openstack_services" }

- hosts:
    - gnocchi-metricd
    - gnocchi-statsd
  roles:
    - { role: gnocchi,
        tags: gnocchi,
        when: "'gnocchi' in openstack_services" }

- hosts:
    - swift-account
    - swift-container
    - swift-object
    - swift-proxy
  roles:
    - { role: swift,
        tags: swift,
        when: "'swift' in openstack_services" }

- hosts:
    - ceilometer-api
    - ceilometer-central
    - ceilometer-collector
    - ceilometer-notification
  roles:
    - { role: ceilometer,
        tags: ceilometer,
        when: "'ceilometer' in openstack_services" }

- hosts:
    - ironic-api
    - ironic-conductor
    - ironic-inspector-dnsmasq
    - ironic-inspector
  roles:
    - { role: ironic,
        tags: ironic,
        when: "'ironic' in openstack_services" }

- hosts:
    - aodh-evaluator
    - aodh-listener
    - aodh-notifier
  roles:
    - { role: aodh,
        tags: aodh,
        when: "'aodh' in openstack_services" }

- hosts:
    - nova-api
    - nova-cert
    - nova-compute
    - nova-conductor
    - nova-scheduler
  roles:
    - { role: nova,
        tags: nova,
        when: "'nova' in openstack_services" }

- hosts:
    - sahara-api
    - sahara-engine
  roles:
    - { role: sahara,
        tags: sahara,
        when: "'sahara' in openstack_services" }

# Should this be only on 1 DB node? (database[0])
- hosts: all
  roles:
    - { role: mariadb,
        tags: mariadb,
        when: "'mariadb' in openstack_services" }
