---
- hosts: all
  roles:
    - { role: puppet_modules,
        tags: puppet_modules }

- hosts: keystone
  roles:
    - { role: keystone,
        tags: keystone,
        when: "'keystone' in openstack_services" }

- hosts:
    - glance-api
    - glance-registry
  roles:
    - { role: glance,
        tags: glance,
        when: "'glance' in openstack_services" }

- hosts:
    - cinder-api
    - cinder-scheduler
    - cinder-volume
  roles:
    - { role: cinder,
        tags: cinder,
        when: "'cinder' in openstack_services" }

- hosts:
    - heat-api
    - heat-api-cfn
    - heat-engine
  roles:
    - { role: heat,
        tags: heat,
        when: "'heat' in openstack_services" }

- hosts:
    - gnocchi-metricd
    - gnocchi-statsd
  roles:
    - { role: gnocchi,
        tags: gnocchi,
        when: "'gnocchi' in openstack_services" }

# Should this be only on 1 DB node? (database[0])
- hosts: all
  roles:
    - { role: mariadb,
        tags: mariadb,
        when: "'mariadb' in openstack_services" }
