---
- name: Gathering overcloud information
  get_heat_output:

- stat: path=/tmp/upgrade-information
  register: info
  failed_when: info.stat.exists == False

- stat: path=/tmp/node-information
  register: nodes
  failed_when: nodes.stat.exists == False

- name: Generating inventory file
  generate_tripleo_inventory:
  become: yes
