---
- name: Starting ceilometer-api service
  command: "/usr/sbin/pcs resource enable openstack-ceilometer-api"
  run_once: true
  when: "inventory_hostname in groups['ceilometer-api']
        and 'ceilometer-api' in pacemaker_managed_services"
  tags: ceilometer_api_pacemaker_start

- name: Starting ceilometer-central service
  command: "/usr/sbin/pcs resource enable openstack-ceilometer-central"
  run_once: true
  when: "inventory_hostname in groups['ceilometer-central']
        and 'ceilometer-central' in pacemaker_managed_services"
  tags: ceilometer_central_pacemaker_start

- name: Starting ceilometer-collector service
  command: "/usr/sbin/pcs resource enable openstack-ceilometer-collector"
  run_once: true
  when: "inventory_hostname in groups['ceilometer-collector']
        and 'ceilometer-collector' in pacemaker_managed_services"
  tags: ceilometer_collector_pacemaker_start

- name: Starting ceilometer-notification service
  command: "/usr/sbin/pcs resource enable openstack-ceilometer-notification"
  run_once: true
  when: "inventory_hostname in groups['ceilometer-notification']
        and 'ceilometer-notification' in pacemaker_managed_services"
  tags: ceilometer_notification_pacemaker_start

- name: Starting ceilometer-compute service
  command: "/usr/sbin/pcs resource enable openstack-ceilometer-compute"
  run_once: true
  when: "inventory_hostname in groups['ceilometer-compute']
        and 'ceilometer-compute' in pacemaker_managed_services"
  tags: ceilometer_compute_pacemaker_start

- name: Waiting for cluster to settle
  command: /usr/sbin/crm_resource --wait
  run_once: true
  tags: [ceilometer_api_pacemaker_start,
         ceilometer_central_pacemaker_start,
         ceilometer_collector_pacemaker_start,
         ceilometer_notification_pacemaker_start,
         ceilometer_compute_pacemaker_start]
