---
- name: Run Ceilometer DB sync
  shell: ceilometer-dbsync --config-file=/etc/ceilometer/ceilometer.conf
  run_once: true
  become: true
  when: "inventory_hostname in groups['ceilometer-api']
        and {{ not update_services | bool }}"
  tags: ceilometer__db_sync
