---
- name: Update ceilometer API package
  yum:
    name: openstack-ceilometer-api
    state: latest
  when: "inventory_hostname in groups['ceilometer-api']"
  become: true
  tags: ceilometer_package_update

- name: Update ceilometer central package
  yum:
    name: openstack-ceilometer-central
    state: latest
  when: "inventory_hostname in groups['ceilometer-central']"
  become: true
  tags: ceilometer_package_update

- name: Update ceilometer collector package
  yum:
    name: openstack-ceilometer-collector
    state: latest
  when: "inventory_hostname in groups['ceilometer-collector']"
  become: true
  tags: ceilometer_package_update

- name: Update ceilometer notification package
  yum:
    name: openstack-ceilometer-notification
    state: latest
  when: "inventory_hostname in groups['ceilometer-notification']"
  become: true
  tags: ceilometer_package_update

- name: Update python ceilometer package
  yum:
    name:
      - python-ceilometer
      - python-ceilometermiddleware
    state: latest
  when: "inventory_hostname in groups['ceilometer-api']
         or inventory_hostname in groups['ceilometer-central']
         or inventory_hostname in groups['ceilometer-collector']
         or inventory_hostname in groups['ceilometer-notification']"
  become: true
  tags: ceilometer_package_update
