---
# This file will be used to upgrade all services
# Any of these variables can be overwritten by upgrade-vars.yml

#############
# Undercloud
#############
undercloud_credentials: "/home/stack/stackrc"

##############
# Update vars
##############
update_services: no

###################
# Upgrade Services
###################
tripleo_services:
  - keystone
  - glance
