---
- name: Running heat DB sync
  shell: heat-manage db_sync
  run_once: true
  become: true
  when: "inventory_hostname in groups['heat-api']
        and {{ not update_services | bool }}"
  tags: heat_db_sync
