---
- name: Update heat packages
  yum:
    name: openstack-heat
    state: latest
  when: "inventory_hostname in groups['heat-api']
        or inventory_hostname in groups['heat-api-cfn']
        or inventory_hostname in groups['heat-engine']"
  tags: heat_package_update
