---
- name: Stopping neutron-dhcp-agent service
  command: "/usr/sbin/pcs resource disable neutron-dhcp-agent"
  run_once: true
  when: "inventory_hostname in groups['neutron-dhcp-agent']
        and 'neutron-dhcp-agent' in pacemaker_managed_services"
  tags: neutron_dhcp_agent_pacemaker_stop

- name: Stopping neutron-l3-agent service
  command: "/usr/sbin/pcs resource disable neutron-l3-agent"
  run_once: true
  when: "inventory_hostname in groups['neutron-l3-agent']
        and 'neutron-l3-agent' in pacemaker_managed_services"
  tags: neutron_l3_agent_pacemaker_stop

- name: Stopping neutron-metadata-agent service
  command: "/usr/sbin/pcs resource disable neutron-metadata-agent"
  run_once: true
  when: "inventory_hostname in groups['neutron-metadata-agent']
        and 'neutron-metadata-agent' in pacemaker_managed_services"
  tags: neutron_metadata_agent_pacemaker_stop

- name: Stopping neutron-openvswitch-agent service
  command: "/usr/sbin/pcs resource disable neutron-openvswitch-agent"
  run_once: true
  when: "inventory_hostname in groups['neutron-openvswitch-agent']
        and 'neutron-openvswitch-agent' in pacemaker_managed_services"
  tags: neutron_openvswitch_agent_pacemaker_stop

- name: Stopping neutron-server service
  command: "/usr/sbin/pcs resource disable neutron-server"
  run_once: true
  when: "inventory_hostname in groups['neutron-server']
        and 'neutron-server' in pacemaker_managed_services"
  tags: nova_scheduler_pacemaker_stop

- name: Waiting for cluster to settle
  command: /usr/sbin/crm_resource --wait
  run_once: true
  tags: [neutron_dhcp_agent_pacemaker_stop,
         neutron_l3_agent_pacemaker_stop,
         neutron_metadata_agent_pacemaker_stop,
         neutron_openvswitch_agent_pacemaker_stop,
         nova_scheduler_pacemaker_stop]
