---
- name: Make sure galera.cnf exists
  file: path=/etc/my.cnf.d/galera.cnf

- name: Make sure Galera replication is active
  blockinfile:
    dest: /etc/my.cnf.d/galera.cnf
    block: |
      [mysqld]
      wsrep_on = ON
      wsrep_cluster_address = gcomm://localhost

- name: Creating /var/lib/mysql
  file: path=/var/lib/mysql state=directory owner=mysql group=mysql mode=0755

- name: Restoring the SELinux label
  command: restorecon -R /var/lib/mysql/
  become: yes

- name: Initialize the new database
  command: mysql_install_db --datadir=/var/lib/mysql --user=mysql

- name: Restore the database
  command: "mysql -u root < {{ database_backup_dri }}/openstack_database.sql"
  register: result

- name: Shutting down the database after the backup
  command: mysqladmin -u root shutdown
  register: result

- name: Remove database backup directory
  command: "rm -rf {{ database_backup_dir }}"
  register: result

- include: enable_fencing.yml

# Uncomment when the services are in the upgrade pipeline
# - name: Pin Messages Nova
#   command: crudini --set /etc/nova/nova.conf upgrade_levels compute "$upgrade_level_nova_compute"
#   when: "inventory_hostname in groups['nova']"

# - name: Pin Messages Ceilometer
#   command: crudini --set /etc/ceilometer/ceilometer.conf DEFAULT rpc_backend rabbit
#   when: "inventory_hostname in groups['ceilometer']"

# - name: Pin Messages Swift
#   command: crudini --set /etc/swift/proxy-server.conf pipeline:main pipeline "catch_errors healthcheck cache ratelimit tempurl formpost authtoken keystone staticweb proxy-logging proxy-server"
#   when: "inventory_hostname in groups['swift']"
