---
- include: database_backup.yml
  when: "inventory_hostname in groups['mariadb']"
  run_once: true
  tags: database_backup

- include: pacemaker_stop_services.yml

- include: move_data.yml
  when: "inventory_hostname in groups['mariadb']"
  run_once: true
  tags: database_backup

- include: shutdown_pacemaker.yml

- include: update_packages.yml

- include: database_setup.yml
  when: "inventory_hostname in groups['mariadb']"
  run_once: true
  tags: database_setup

- include: startup_pacemaker.yml

- include: pacemaker_start_services.yml
