---
- name: Stopping mariadb service
  command: "/usr/sbin/pcs resource disable galera"
  run_once: true
  when: "inventory_hostname in groups['mariadb']
        and 'mariadb' in pacemaker_managed_services"
  tags: mariadb_pacemaker_stop

- name: Waiting for cluster to settle
  command: /usr/sbin/crm_resource --wait
  run_once: true
  when: "inventory_hostname in groups['mariadb']
        and 'mariadb' in pacemaker_managed_services"
  tags: mariadb_pacemaker_stop
