---
- name: Stopping mariadb service
  service:
    name: galera
    state: stopped
  become: yes
  when: "inventory_hostname in groups['mariadb']
        and 'mariadb' not in pacemaker_managed_services"
  tags: mariadb_systemd_stop
