---
- include: pacemaker.yml
  when: "'mariadb' in pacemaker_managed_services"
  tags: mariadb_pacemaker_tasks

- include: systemd.yml
  when: "'mariadb' not in pacemaker_managed_services"
  tags: mariadb_systemd_tasks
