---
- name: Removing delorean repo file
  file: path=/etc/yum.repos.d/delorean.repo state=absent
  become: yes

- name: Pulling the new repo
  get_url: url="{{ delorean_repo_url }}" dest=/etc/yum.repos.d/delorean.repo
  become: yes
