---
# Would this only happend on Mariadb[0]?
- name: Enable Fencing
  command: pcs -f /var/lib/pacemaker/cib/cib.xml property set stonith-enabled=true
  when: "inventory_hostname in groups[item]"
  with_items: "{{ pacemaker_managed_services }}"
  tags: enable_fencing
