---
- name: Shutting down Pacemaker
  command: /usr/sbin/pcs cluster stop --all
  when: "inventory_hostname in groups[item]"
  with_items: "{{ pacemaker_managed_services }}"
  tags: pacemaker_stop

- name: Waiting for Pacemaker to stop
  command: systemctl is-active pacemaker
  register: pacemaker_result
  until: pacemaker_result.stdout == 'inactive'
  retries: 10
  delay: 5
  when: "inventory_hostname in groups[item]"
  with_items: "{{ pacemaker_managed_services }}"
  tags: pacemaker_stop
