---
- name: Stopping aodh-evaluator service
  service:
    name: openstack-aodh-evaluator
    state: stopped
  become: yes
  when: "inventory_hostname in groups['aodh-evaluator']
        and 'aodh-evaluator' not in pacemaker_managed_services"
  tags: aodh_evaluator_systemd_stop

- name: Stopping aodh-listener service
  service:
    name: openstack-aodh-listener
    state: stopped
  become: yes
  when: "inventory_hostname in groups['aodh-listener']
        and 'aodh-listener' not in pacemaker_managed_services"
  tags: aodh_listener_systemd_stop

- name: Stopping aodh-notifier service
  service:
    name: openstack-aodh-notifier
    state: stopped
  become: yes
  when: "inventory_hostname in groups['aodh-notifier']
        and 'aodh-notifier' not in pacemaker_managed_services"
  tags: aodh_notifier_systemd_stop
