---
- name: Stopping gnocchi-metricd service
  command: "/usr/sbin/pcs resource disable openstack-gnocchi-metricd"
  run_once: true
  when: "inventory_hostname in groups['gnocchi-metricd']
        and 'gnocchi-metricd' in pacemaker_managed_services"
  tags: gnocchi_metricd_pacemaker_stop

- name: Stopping gnocchi-statsd service
  command: "/usr/sbin/pcs resource disable openstack-gnocchi-statsd"
  run_once: true
  when: "inventory_hostname in groups['gnocchi-statsd']
        and 'gnocchi-statsd' in pacemaker_managed_services"
  tags: gnocchi_statsd_pacemaker_stop

- name: Waiting for cluster to settle
  command: /usr/sbin/crm_resource --wait
  run_once: true
  tags: [gnocchi_metricd_pacemaker_stop, gnocchi_statsd_pacemaker_stop]
