---
# Should this be run for metricd or statsd?
- name: Run gnocchi DB sync
  shell: gnocchi-manage db_sync
  run_once: true
  become: true
  when: "inventory_hostname in groups['gnocchi-metricd']
        and {{ not update_services | bool }}"
  tags: gnocchi_db_sync
