---
- name: Starting gnocchi-metricd service
  service:
    name: openstack-gnocchi-metricd
    state: started
  become: yes
  when: "inventory_hostname in groups['gnocchi-metricd']
        and 'gnocchi-metricd' not in pacemaker_managed_services"
  tags: gnocchi_metricd_systemd_start

- name: Starting gnocchi-statsd service
  service:
    name: openstack-gnocchi-statsd
    state: started
  become: yes
  when: "inventory_hostname in groups['gnocchi-statsd']
        and 'gnocchi-statsd' not in pacemaker_managed_services"
  tags: gnocchi_statsd_systemd_start
