---
- name: Stopping gnocchi-metricd service
  service:
    name: openstack-gnocchi-metricd
    state: stopped
  become: yes
  when: "inventory_hostname in groups['gnocchi-metricd']
        and 'gnocchi-metricd' not in pacemaker_managed_services"
  tags: gnocchi_metricd_systemd_stop

- name: Stopping gnocchi-statsd service
  service:
    name: openstack-gnocchi-statsd
    state: stopped
  become: yes
  when: "inventory_hostname in groups['gnocchi-statsd']
        and 'gnocchi-statsd' not in pacemaker_managed_services"
  tags: gnocchi_statsd_systemd_stop
