---
- include: pacemaker.yml
  when: "'gnocchi-metricd' in pacemaker_managed_services
        or 'gnocchi-statsd' in pacemaker_managed_services"
  tags: gnocchi_pacemaker_tasks

- include: systemd.yml
  when: "'gnocchi-metricd' not in pacemaker_managed_services
        or 'gnocchi-statsd' not in pacemaker_managed_services"
  tags: gnocchi_systemd_tasks
