---
- name: Stopping keystone service
  command: "/usr/sbin/pcs resource disable httpd"
  run_once: true
  when: inventory_hostname in groups['keystone']
  tags: keystone_pacemaker_stop

- name: Waiting for cluster to settle
  command: /usr/sbin/crm_resource --wait
  run_once: true
  when: inventory_hostname in groups['keystone']
  tags: keystone_pacemaker_stop
