---
- name: Update keystone packages
  yum:
    name:
      - openstack-keystone
      - httpd
    state: latest
  when: "inventory_hostname in groups['keystone']"
  become: true
  tags: keystone_package_update

- name: Update python keystone packages
  yum:
    name:
      - python-keystone
      - python-keystonemiddleware
    state: latest
  when: "inventory_hostname in groups['keystone']"
  become: true
  tags: keystone_package_update
