---
- name: Starting nova-api service
  command: "/usr/sbin/pcs resource enable openstack-nova-api"
  run_once: true
  when: "inventory_hostname in groups['nova-api']
        and 'nova-api' in pacemaker_managed_services"
  tags: nova_api_pacemaker_start

- name: Starting nova-cert service
  command: "/usr/sbin/pcs resource enable openstack-nova-cert"
  run_once: true
  when: "inventory_hostname in groups['nova-cert']
        and 'nova-cert' in pacemaker_managed_services"
  tags: nova_cert_pacemaker_start

- name: Starting nova-conductor service
  command: "/usr/sbin/pcs resource enable openstack-nova-conductor"
  run_once: true
  when: "inventory_hostname in groups['nova-conductor']
        and 'nova-conductor' in pacemaker_managed_services"
  tags: nova_conductor_pacemaker_start

- name: Starting nova-scheduler service
  command: "/usr/sbin/pcs resource enable openstack-nova-scheduler"
  run_once: true
  when: "inventory_hostname in groups['nova-scheduler']
        and 'nova-scheduler' in pacemaker_managed_services"
  tags: nova_scheduler_pacemaker_start

- name: Starting nova-compute service
  command: "/usr/sbin/pcs resource enable openstack-nova-compute"
  run_once: true
  when: "inventory_hostname in groups['nova-compute']
        and 'nova-compute' in pacemaker_managed_services"
  tags: nova_compute_pacemaker_start

- name: Waiting for cluster to settle
  command: /usr/sbin/crm_resource --wait
  run_once: true
  tags: [nova_api_pacemaker_start,
         nova_cert_pacemaker_start,
         nova_compute_pacemaker_start,
         nova_conductor_pacemaker_start,
         nova_scheduler_pacemaker_start]
