---
- name: Run Nova DB sync
  shell: nova-manage db_sync
  run_once: true
  become: true
  when: "inventory_hostname in groups['nova-api']
        and {{ not update_services | bool }}"
  tags: nova_db_sync
