---
- name: Stopping nova-api service
  service:
    name: openstack-nova-api
    state: stopped
  become: yes
  when: "inventory_hostname in groups['nova-api']
        and 'nova-api' not in pacemaker_managed_services"
  tags: nova_api_systemd_stop

- name: Stopping nova-cert service
  service:
    name: openstack-nova-cert
    state: stopped
  become: yes
  when: "inventory_hostname in groups['nova-cert']
        and 'nova-cert' not in pacemaker_managed_services"
  tags: nova_cert_systemd_stop

- name: Stopping nova-compute service
  service:
    name: openstack-nova-compute
    state: stopped
  become: yes
  when: "inventory_hostname in groups['nova-compute']
        and 'nova-compute' not in pacemaker_managed_services"
  tags: nova_compute_systemd_stop

- name: Stopping nova-conductor service
  service:
    name: openstack-nova-conductor
    state: stopped
  become: yes
  when: "inventory_hostname in groups['nova-conductor']
        and 'nova-conductor' not in pacemaker_managed_services"
  tags: nova_conductor_systemd_stop

- name: Stopping nova-scheduler service
  service:
    name: openstack-nova-scheduler
    state: stopped
  become: yes
  when: "inventory_hostname in groups['nova-scheduler']
        and 'nova-scheduler' not in pacemaker_managed_services"
  tags: nova_scheduler_systemd_stop
