---
- name: Starting nova-api service
  service:
    name: openstack-nova-api
    state: started
  become: yes
  when: "inventory_hostname in groups['nova-api']
        and 'nova-api' not in pacemaker_managed_services"
  tags: nova_api_systemd_start

- name: Starting nova-cert service
  service:
    name: openstack-nova-cert
    state: started
  become: yes
  when: "inventory_hostname in groups['nova-cert']
        and 'nova-cert' not in pacemaker_managed_services"
  tags: nova_cert_systemd_start

- name: Starting nova-compute service
  service:
    name: openstack-nova-compute
    state: started
  become: yes
  when: "inventory_hostname in groups['nova-compute']
        and 'nova-compute' not in pacemaker_managed_services"
  tags: nova_compute_systemd_start

- name: Starting nova-conductor service
  service:
    name: openstack-nova-conductor
    state: started
  become: yes
  when: "inventory_hostname in groups['nova-conductor']
        and 'nova-conductor' not in pacemaker_managed_services"
  tags: nova_conductor_systemd_start

- name: Starting nova-scheduler service
  service:
    name: openstack-nova-scheduler
    state: started
  become: yes
  when: "inventory_hostname in groups['nova-scheduler']
        and 'nova-scheduler' not in pacemaker_managed_services"
  tags: nova_scheduler_systemd_start
