---
- name: Update nova-api package
  yum:
    name: openstack-nova-api
    state: latest
  when: "inventory_hostname in groups['nova-api']"
  become: true
  tags: nova_package_update

- name: Update nova-cert package
  yum:
    name: openstack-nova-cert
    state: latest
  when: "inventory_hostname in groups['nova-cert']"
  become: true
  tags: nova_package_update

- name: Update nova-compute package
  yum:
    name: openstack-nova-compute
    state: latest
  when: "inventory_hostname in groups['nova-compute']"
  become: true
  tags: nova_package_update

- name: Update nova-conductor package
  yum:
    name: openstack-nova-conductor
    state: latest
  when: "inventory_hostname in groups['nova-conductor']"
  become: true
  tags: nova_package_update

- name: Update nova-scheduler package
  yum:
    name: openstack-nova-scheduler
    state: latest
  when: "inventory_hostname in groups['nova-scheduler']"
  become: true
  tags: nova_package_update

- name: Update python nova package
  yum:
    name: python-nova
    state: latest
  when: "inventory_hostname in groups['nova-api']
         or inventory_hostname in groups['nova-cert']
         or inventory_hostname in groups['nova-compute']
         or inventory_hostname in groups['nova-conductor']
         or inventory_hostname in groups['nova-scheduler']"
  become: true
  tags: nova_package_update
